name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: |
          yarn install
      - name: yarn typecheck
        run: |
          yarn typecheck
      - name: yarn test
        run: |
          yarn test
